version: '3.1'
services:
  app:
    container_name: renato-cliente
    image: renato-cliente
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=a
      - POSTGRES_USER=postgres
      - POSTGRES_DB=clientes
